#------------------------------
#server 相关配置
#------------------------------
server:
    session:
        cookie:
            http-only: true

#------------------------------
#spring 相关配置
#------------------------------
spring:
    application:
        name: crazy-admin
    profiles:
        active: default, dev
    output:
        ansi:
          enabled: detect
    mvc:
        favicon:
            enabled: false

#公共属性
application:
    base-package: com.crazy.coding

#------------------------------
#日志相关配置
#------------------------------
logging:
    path: /app/logs

#------------------------------
#mybatis配置信息
#------------------------------
mybatis:
    configuration:
        #开启驼峰转换
        map-underscore-to-camel-case: true
    #mapper.xml文件的路径
    mapper-locations: classpath*:mapper/*.xml
    #实体类的位置
    type-aliases-package: ${application.base-package}.entity