
#创建用户表#
CREATE TABLE `user` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '帐号',
  `password` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '密码',
  `name` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '姓名',
  `age` INT(4) NOT NULL DEFAULT '0' COMMENT '年龄',
  `comment` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后更新时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
